//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagementMvc.Statics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagementMvc.Statics.StaticMessages", typeof(StaticMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course is not found.
        /// </summary>
        internal static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course is created successfully!.
        /// </summary>
        internal static string CreatedCourse {
            get {
                return ResourceManager.GetString("CreatedCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is created!.
        /// </summary>
        internal static string CreatedGroup {
            get {
                return ResourceManager.GetString("CreatedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson is created!.
        /// </summary>
        internal static string CreatedLesson {
            get {
                return ResourceManager.GetString("CreatedLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is created!.
        /// </summary>
        internal static string CreatedStudent {
            get {
                return ResourceManager.GetString("CreatedStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is created!.
        /// </summary>
        internal static string CreatedSubject {
            get {
                return ResourceManager.GetString("CreatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher is created!.
        /// </summary>
        internal static string CreatedTeacher {
            get {
                return ResourceManager.GetString("CreatedTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course deleted successfully.
        /// </summary>
        internal static string DeletedCourse {
            get {
                return ResourceManager.GetString("DeletedCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is deleted successfully!.
        /// </summary>
        internal static string DeletedGroup {
            get {
                return ResourceManager.GetString("DeletedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson is deleted!.
        /// </summary>
        internal static string DeletedLesson {
            get {
                return ResourceManager.GetString("DeletedLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is deleted!.
        /// </summary>
        internal static string DeletedStudent {
            get {
                return ResourceManager.GetString("DeletedStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is deleted!.
        /// </summary>
        internal static string DeletedSubject {
            get {
                return ResourceManager.GetString("DeletedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher is deleted!.
        /// </summary>
        internal static string DeletedTeacher {
            get {
                return ResourceManager.GetString("DeletedTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not exists..
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is not found..
        /// </summary>
        internal static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson not found..
        /// </summary>
        internal static string LessonNotFound {
            get {
                return ResourceManager.GetString("LessonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned mark successfully!.
        /// </summary>
        internal static string MarkAssign {
            get {
                return ResourceManager.GetString("MarkAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deatil is null!.
        /// </summary>
        internal static string NullFile {
            get {
                return ResourceManager.GetString("NullFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is not found!.
        /// </summary>
        internal static string StudentNotFound {
            get {
                return ResourceManager.GetString("StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is not found..
        /// </summary>
        internal static string SubjectNotFound {
            get {
                return ResourceManager.GetString("SubjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher is not found..
        /// </summary>
        internal static string TeacherNotFound {
            get {
                return ResourceManager.GetString("TeacherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course is updated successfully!.
        /// </summary>
        internal static string UpdatedCourse {
            get {
                return ResourceManager.GetString("UpdatedCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is updated successfully!.
        /// </summary>
        internal static string UpdatedGroup {
            get {
                return ResourceManager.GetString("UpdatedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson is updated successfully!.
        /// </summary>
        internal static string UpdatedLesson {
            get {
                return ResourceManager.GetString("UpdatedLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is updated!.
        /// </summary>
        internal static string UpdatedStudent {
            get {
                return ResourceManager.GetString("UpdatedStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student groups are updated!.
        /// </summary>
        internal static string UpdatedStudentGroups {
            get {
                return ResourceManager.GetString("UpdatedStudentGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is updated!.
        /// </summary>
        internal static string UpdatedSubject {
            get {
                return ResourceManager.GetString("UpdatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher is updated!.
        /// </summary>
        internal static string UpdatedTeacher {
            get {
                return ResourceManager.GetString("UpdatedTeacher", resourceCulture);
            }
        }
    }
}
